// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SharedDB;

#nullable disable

namespace SharedDB.Migrations
{
    [DbContext(typeof(SharedDbContext))]
    [Migration("20240316023055_Expired")]
    partial class Expired
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SharedDB.ServerInfoDb", b =>
                {
                    b.Property<int>("ServerInfoDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServerInfoDbId"));

                    b.Property<int>("BusyCcore")
                        .HasColumnType("int");

                    b.Property<string>("ServerIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ServerPort")
                        .HasColumnType("int");

                    b.HasKey("ServerInfoDbId");

                    b.HasIndex("ServerName")
                        .IsUnique();

                    b.ToTable("ServerInfo");
                });

            modelBuilder.Entity("SharedDB.TokenDb", b =>
                {
                    b.Property<int>("TokenDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TokenDbId"));

                    b.Property<int>("AccountDbId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Expired")
                        .HasColumnType("datetime2");

                    b.Property<int>("Token")
                        .HasColumnType("int");

                    b.HasKey("TokenDbId");

                    b.HasIndex("AccountDbId")
                        .IsUnique();

                    b.ToTable("Token");
                });
#pragma warning restore 612, 618
        }
    }
}
